name: 'Deploy to Server'

on:
  workflow_call:

jobs:
  build:
    name: 'deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 18

      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle jar 빌드
      - name: Build jar with Gradle
        run: ./gradlew jar

      # 빌드된 jar 파일을 서버로 전송
      - name: copy jar file via ssh password
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./build/libs/deploy.jar"
          target: "~/test/"
          strip_components: 2