name: 'CI/CD'

on:
  push:
    branches: [master]

jobs:
  call_testing:
    uses: ./.github/workflows/junit.yml
    secrets: inherit

  # call_deploy 호출 전 call_testing 체이닝
  call_deploy:
    uses: ./.github/workflows/deploy.yml
    needs: call_testing
    secrets: inherit